ALTER TABLE async_job
  MODIFY COLUMN tipo ENUM(
    'IMPORTACAO_PRODUTO',
    'EXCLUSAO_MASSIVA',
    'ALTERACAO_ATRIBUTOS',
    'AJUSTE_ESTRUTURA',
    'APLICACAO_AJUSTE_ESTRUTURA',
    'AJUSTE_ESTRUTURA_CATALOGO',
    'EXPORTACAO_PRODUTO',
    'EXPORTACAO_FABRICANTE',
    'TRANSMISSAO_PRODUTO'
  ) NOT NULL;
