networks:
  app-network:
    driver: bridge

services:
  # === Backend (API Node/Express + Prisma) ===
  backend:
    build:
      context: ./backend
    container_name: catalogo-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.docker
    networks:
      - app-network

  # === Frontend Next.js ===
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
    container_name: catalogo-frontend
    ports:
      - '3001:3000'
    env_file:
      - ./frontend/.env.docker
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000/api
    depends_on:
      - backend
    networks:
      - app-network