version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  # === Backend (API Node/Express + Prisma) ===
  backend:
    build:
      context: ./backend
    container_name: catalogo-backend
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.docker
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - LEGACY_PASSWORD_SALT=${LEGACY_PASSWORD_SALT}
    networks:
      - app-network

  # === Frontend Next.js ===
  frontend:
    build:
      context: ./frontend
    container_name: catalogo-frontend
    ports:
      - '3001:3000'
    env_file:
      - ./frontend/.env.local
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - app-network